on:
  push:
    branches:
      - main

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.JWKS_RELEASE_PLEASE_PAT }}
          release-type: rust
  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created
    environment: crates.io
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: swatinem/rust-cache@v2
      - run: cargo publish --token ${{ secrets.JWKS_CARGO_REGISTRY_TOKEN }}